name: Flutter Multi-platform Build CI

on:
  push:
    tags:
      - v*

permissions:
  contents: write

jobs:
  build:
    env:
      JAVA_OPTS: '-Xmx4g' # Give Java 4GB of RAM
      GRADLE_OPTS: '-Dorg.gradle.jvmargs=-Xmx4g'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            flutter_os: linux
            archive_path: build/linux/x64/release/bundle/
            artifact_name: release.tar.gz
            asset_name: dnschat-linux-${{ github.ref_name }}.tar.gz
          - os: ubuntu-latest
            flutter_os: apk
            archive_path: -1
            artifact_name: build/app/outputs/flutter-apk/app-release.apk
            asset_name: dnschat-android-${{ github.ref_name }}.apk
          - os: windows-latest
            flutter_os: windows
            archive_path: build\windows\x64\runner\Release
            artifact_name: release.zip
            asset_name: dnschat-windows-${{ github.ref_name }}.zip
          - os: macos-latest
            flutter_os: macos
            archive_path: build/macos/Build/Products/Release/dnschat.app
            dmg_name: release
            artifact_name: release.dmg
            asset_name: dnschat-macos-${{ github.ref_name }}.dmg
          # - os: macos-latest
          #   flutter_os: ios
          #   archive_path: build/ios/ipa/
          #   artifact_name: release.zip
          #   asset_name: dnschat-ios-${{ github.ref_name }}.zip
    runs-on: ${{ matrix.os }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          lfs: true
      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          pub-cache: true
      - name: Prepare APT
        if: matrix.flutter_os == 'linux'
        run: |
          sudo apt update -y
      - name: Linux dependencies
        if: matrix.flutter_os == 'linux'
        uses: awalsh128/cache-apt-pkgs-action@v1
        with:
          packages: ninja-build libgtk-3-dev libwebkit2gtk-4.1-dev
          version: 1.0
      - name: Create temporary keychain
        if: matrix.flutter_os == 'macos'
        continue-on-error: true
        run: |
          KEYCHAIN_NAME=temp_build.keychain-db
          KEYCHAIN_PASSWORD=$(openssl rand -base64 32)
          echo "Creating temporary keychain: $KEYCHAIN_NAME"
          security create-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_NAME"
          security default-keychain -s "$KEYCHAIN_NAME"
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" "$KEYCHAIN_NAME"
          security list-keychains -d user -s "$KEYCHAIN_NAME"
          echo "password=$KEYCHAIN_PASSWORD" >> $GITHUB_OUTPUT
          echo "FASTLANE_KEYCHAIN_PATH=$KEYCHAIN_NAME" >> $GITHUB_ENV
          echo "FASTLANE_KEYCHAIN_PASSWORD=$KEYCHAIN_PASSWORD" >> $GITHUB_ENV
      - name: Build
        run: |
          flutter build ${{ matrix.flutter_os }} --release
      # - name: List files (Debug)
      #   run: ls -R build/
      - name: Install Modern Bash on macOS
        if: matrix.flutter_os == 'macos'
        uses: tecolicom/actions-use-homebrew-tools@v1
        continue-on-error: true
        with:
          tools: bash
      - name: Archive - Multi-platform
        if: >
          matrix.flutter_os != 'windows' &&
          matrix.flutter_os != 'macos' &&
          matrix.archive_path != -1
        shell: bash
        run: |
          original_path=$(pwd)
          cd ${{ matrix.archive_path }}
          tar cvzf $original_path/${{ matrix.artifact_name }} .
          cd $original_path
      - name: Archive - Windows
        if: matrix.flutter_os == 'windows'
        shell: cmd
        run: |
          set "ORIGINAL_PATH=%CD%"
          cd /d "${{ matrix.archive_path }}"
          tar -a -c -f "%ORIGINAL_PATH%/${{ matrix.artifact_name }}" *
          cd /d "%ORIGINAL_PATH%"
      - name: Archive - MacOS
        if: matrix.flutter_os == 'macos'
        uses: L-Super/create-dmg-actions@v1
        with:
          dmg_name: ${{ matrix.dmg_name }}
          src_dir: ${{ matrix.archive_path }}
      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
      - name: Delete temporary keychain
        if: matrix.flutter_os == 'macos'
        continue-on-error: true
        run: |
          KEYCHAIN_NAME=temp_build.keychain-db
          echo "Deleting keychain $KEYCHAIN_NAME"
          security delete-keychain "$KEYCHAIN_NAME" || echo "Keychain not found or already deleted"
